flask-app:
  image: python:3.6
  services:
  - postgres:latest

  variables:
    POSTGRES_DB: flask_blog
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
  script:
    - export DATABASE_URL=postgres://runner@postgres:5432/flask_blog
    - apt-get update -qy
    - apt-get install -y python3-dev python-pip
    - pip install -r requirements.txt
    - nosetests --with-coverage --cover-erase --cover-package=flaskr
