flask-app:
  image: python:3.6
  script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/flask-blog
    - apt-get update -qy
    - apt-get install -y python3-dev python-pip
    - pip install -r requirements.txt
    - nosetests --with-coverage --cover-erase --cover-package=flaskr
