test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/flask-blog
  - apt-get update -qy
  - apt-get install -y python3.6-dev python-pip
  - pip install -r requirements.txt
  - nosetests --with-coverage --cover-erase --cover-package=flaskr
